- name: Write hostname and touch temp 
  hosts: all
  tasks:
  - name: Write hostname using jinja2
    ansible.builtin.template:
      src: templates/test.j2
      dest: /tmp/hostname

  - name: Touch files with an optional mode
    ansible.builtin.file:
      dest: "{{ item.path }}"
      state: touch
      mode: "{{ item.mode | default(omit) }}"
    loop:
      - path: /tmp/foo
      - path: /tmp/bar
      - path: /tmp/baz
        mode: "0444"

  - name: Warn if this file does not exist, but continue
    debug: msg="{{ lookup('file', '/nosuchfile', errors='warn') }}"
